### PR TITLE
Fixes the issues with the buffers crashing

### LINKED ISSUE #15: Move the code to use storeBytes instead of pointers
```swift
        ensureSpace(size: UInt8(len))
        let pointer = UnsafeMutablePointer<T.NumaricValue>.allocate(capacity: len)
        pointer.initialize(to: value.convertedEndian)
        write(pointer: pointer, len: len, index: writerIndex)
        pointer.deallocate()
        _writerSize += len
```
the current implementation uses the following to create the buffer, however we can use the storeBytes function that's already implemented by apple to add the values.

known issues: Always getting a `storeBytes to misaligned raw pointer` error

### LINKED ISSUE #16: Need for relocation for each add
On the following line:

https://github.com/mustiikhalil/FlatBuffer/blob/2cc23c22eeaa355b248cc66eabbd8f48f7589b2d/Sources/FlatBuffers/FlatBuffer.swift#L98

The capacity is increased only by immediately needed size. This means that on the next add we will have to reallocate again. In order to avoid frequent memory reallocation, it is considered a good practice to double the given capacity when it becomes insufficient. It would be also ok to have a fix capacity increase number, if we are concerned with memory consumption. But reallocating on every add is a very expensive operation, which can be avoided only if user knows the exact capacity size upfront.

### LINKED ISSUE #17: Probably no need to zero out the memory again
On following line, we zero out the memory on padding:
https://github.com/mustiikhalil/FlatBuffer/blob/2cc23c22eeaa355b248cc66eabbd8f48f7589b2d/Sources/FlatBuffers/FlatBuffer.swift#L44

This seems unnecessary to me as we are performing memory initialisation which is zeroing out the memory space on init:
https://github.com/mustiikhalil/FlatBuffer/blob/25994cc8072196f3cc6229b02c233f74be781a3a/Sources/FlatBuffers/FlatBuffer.swift#L20

And on reallocate:
https://github.com/mustiikhalil/FlatBuffer/blob/25994cc8072196f3cc6229b02c233f74be781a3a/Sources/FlatBuffers/FlatBuffer.swift#L84

I might miss so kind of a use case though.

### PR DESCRIPTION
**Pull request by mustiikhalil**
The following PR fixes the issue that we have been facing regarding the memory management and deallocation. we fixed this by moving the logic from writing using pointers into writing using `storeBytes`. I read the logic that you implemented in the following [repository](https://github.com/mzaks/FlatBuffersSwift) when creating the strings, and moved the entire logic to use the same function storeBytes since that seemed to solve the issue with the crashes and memory allocation

Fixes #15 and Closes #16 and Closes #17

### CODE REVIEW

File: Sources/FlatBuffers/Constants.swift [hunk 1]
```diff
@@ -5,47 +5,47 @@ import Foundation
...
-    var convertedEndian: NumaricValue {
+    public var convertedEndian: NumaricValue {
         if isLitteEndian { return self as! Self.NumaricValue }
         return self.littleEndian as! Self.NumaricValue
     }
 }
 
 extension Double: Scaler {
-    typealias NumaricValue = UInt64
+    public typealias NumaricValue = UInt64
```
Comment (mzaks) [inline Sources/FlatBuffers/Constants.swift]: Small thing, but I think it should be called NumericValue

File: Sources/FlatBuffers/Constants.swift [hunk 2]
```diff
@@ -5,47 +5,47 @@ import Foundation
...
 
 extension Scaler where Self: FixedWidthInteger {
-    var convertedEndian: NumaricValue {
+    public var convertedEndian: NumaricValue {
         if isLitteEndian { return self as! Self.NumaricValue }
         return self.littleEndian as! Self.NumaricValue
     }
 }
 
 extension Double: Scaler {
```
Comment (mzaks) [inline Sources/FlatBuffers/Constants.swift]: Here also a small thing, I think the correct term is Scalar (https://en.wikipedia.org/wiki/Scalar_(mathematics))

File: Sources/FlatBuffers/FlatBuffer.swift [hunk 3]
```diff
@@ -1,22 +1,24 @@
 import Foundation
+import os.log
```
Comment (mzaks) [inline Sources/FlatBuffers/FlatBuffer.swift]: Do we really want to keep it. It's fine if we do, but it looks like a "debugging" tool forgotten to be cleaned up.

File: Sources/FlatBuffers/FlatBuffer.swift [hunk 4]
```diff
@@ -1,22 +1,24 @@
...
+    var alignment = 1
+    
+    public var writerIndex: Int { return _capacity - _writerSize }
+    public var size: UOffset { return UOffset(_writerSize) }
+    public var memory: UnsafeMutableRawPointer { return _memory }
+    public var capacity: Int { return _capacity }
     
     ///
     /// - Parameter size:
     init(initialSize size: Int) {
```
Comment (mzaks) [inline Sources/FlatBuffers/FlatBuffer.swift]: We should probably check if the size is bigger than 0. Not sure what will happen if allocating with negative size. Also it might make sense to use an unsigned integer here, however `Int` is the default numeric type in Swift, so not sure if it is useful. Maybe assertion is just enough.

File: Sources/FlatBuffers/FlatBuffer.swift [hunk 5]
```diff
@@ -28,77 +30,80 @@ struct FlatBuffer {
         _capacity = bytes.count
     }
     
+    deinit {
+        _memory.deallocate()
+        os_log("Deinit Flatbuffer object", type: .debug)
```
Comment (mzaks) [inline Sources/FlatBuffers/FlatBuffer.swift]: Same is with import, not sure if it makes sense to have such logging in production code.

File: Sources/FlatBuffers/FlatBuffer.swift (hunk 4 above)
Comment (mzaks) [reply Sources/FlatBuffers/FlatBuffer.swift]: On another thought, if it is not public API then it is fine.

File: Sources/FlatBuffers/FlatBuffersBuilder.swift [hunk 6]
```diff
@@ -1,42 +1,49 @@
 import Foundation
-
+import os.log
```
Comment (mzaks) [inline Sources/FlatBuffers/FlatBuffersBuilder.swift]: Need to check if os logging is desirable in production code. (See comments above)

File: Sources/FlatBuffers/FlatBuffer.swift (hunk 4 above)
Comment (mustiikhalil) [reply Sources/FlatBuffers/FlatBuffer.swift]: I think Users should only be allowed to allocate a buffer through the builder, or use `init(bytes: [UInt8])`

**Comment by mustiikhalil** [comment]
Sounds, good!
